name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Validate manifest
              run: |
                  # Check if manifest.json is valid JSON
                  jq empty manifest.json

                  # Check version format (semantic versioning)
                  VERSION=$(jq -r '.version' manifest.json)
                  if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                    echo "Invalid version format: $VERSION"
                    exit 1
                  fi
                  echo "Version $VERSION is valid"

            - name: Test build process
              run: |
                  make clean
                  make web-ext-artifacts/webext.zip

                  # Verify build artifacts exist
                  if [ ! -f "web-ext-artifacts/webext.zip" ]; then
                    echo "Build failed: webext.zip not found"
                    exit 1
                  fi

                  echo "Build successful"
